"""Project defaults shared by pipeline components."""

BINANCE_BASE_URL = "https://data.binance.vision"
OHLCV_INTERVAL = "5m"
WINDOW_HOURS = 24.0
ZSCORE_THRESHOLD = 2.5
DRAWDOWN_HOURS = 4.0
DRAWDOWN_THRESHOLD = 0.50
RETURN_HOURS = 2.0
RETURN_THRESHOLD = 0.25
MAX_GAP = 6
MIN_CONSECUTIVE = 2
FUNDING_RATE_THRESHOLD = 0.0005
OI_CHANGE_THRESHOLD = 0.10
LLM_MODEL = "glm-5.2-short"
